/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_package;

import file_op.FileOperations;
import java.awt.Color;
import java.awt.HeadlessException;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/**
 *
 * @author Doreen Midecha
 */
public class codes extends javax.swing.JFrame {
FileOperations fo;
    thread_file_2 tf;
    /**
     * Creates new form codes
     */
    public codes() {
        initComponents();
        tf = new thread_file_2(new writing_splash(), 40, new eim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        print_chk = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        office_key_chk = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        tel_chk = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        alarm_chk = new javax.swing.JCheckBox();
        codes_quit_btn = new javax.swing.JButton();
        codes_app_commit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alarm_office_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        open_off_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        print_chk.setText("Yes");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("PRINTING :");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        office_key_chk.setText("Yes");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("OFFICE KEYS :");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tel_chk.setText("Yes");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("TELEPHONE :");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("ALARM :");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        alarm_chk.setText("Yes");

        codes_quit_btn.setText("Quit");
        codes_quit_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codes_quit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                codes_quit_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                codes_quit_btnMouseExited(evt);
            }
        });
        codes_quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codes_quit_btnActionPerformed(evt);
            }
        });

        codes_app_commit_btn.setBackground(new java.awt.Color(153, 255, 153));
        codes_app_commit_btn.setText("Commit");
        codes_app_commit_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        codes_app_commit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codes_app_commit_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("SPECIFY OFFICE:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("SPECIFY OFFICE:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel1)
                    .addComponent(jLabel22))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(codes_quit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(open_off_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(office_key_chk))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codes_app_commit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarm_chk)
                            .addComponent(alarm_office_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print_chk)
                            .addComponent(tel_chk))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codes_quit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(tel_chk))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print_chk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alarm_chk))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(alarm_office_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(office_key_chk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codes_app_commit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(open_off_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codes_quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codes_quit_btnActionPerformed
        //       display control
        new login().setVisible(true);
        //        dispose this jframe
        dispose();
    }//GEN-LAST:event_codes_quit_btnActionPerformed

    private void codes_app_commit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codes_app_commit_btnActionPerformed
        boolean tel = tel_chk.isSelected();
        boolean print = print_chk.isSelected();
        boolean alarm = alarm_chk.isSelected();
        String alarm_office = alarm_office_txt.getText();
        boolean office_keys = office_key_chk.isSelected();
        String office = open_off_txt.getText();
        String[] codes = new String[7];
        codes[0] = "**CODES**";
        if (tel) {
            codes[1] = "TELEPHONE CODES_ _: TRUE";
        } else {
            codes[1] = "TELEPHONE CODES_ _: FALSE";
        }
        if (print) {
            codes[2] = "PRINTING CODES_ _ : TRUE";
        } else {
            codes[2] = "PRINTING CODES_ _ : FALSE";
        }
        if (alarm) {
            codes[3] = "ALARM CODES _ _ _ : TRUE";
            codes[4] = "ALARM OFFICE_ _ _ : " + alarm_office.toUpperCase();
        } else {
            codes[3] = "ALARM CODES _ _ _ : FALSE";
            codes[4] = "ALARM OFFICE_ _ _ : FALSE";
        }
        if (office_keys) {
            codes[5] = "OFFICE KEYS _ _ _ : TRUE";
            codes[6] = "OPEN OFFICE_ _ _ _: " + office.toUpperCase();
        } else {
            codes[5] = "OFFICE KEYS _ _ _ : FALSE";
            codes[6] = "OPEN OFFICE_ _ _ _: FALSE";
        }
        fo = new FileOperations();
        try {
            if (fo.fileExists()) {
//                close this frmae 
                dispose();
//          start file thread
                tf.start();
//                write to file
                try {
                    fo.writeToFile(codes);
                } catch (NullPointerException e) {
                    System.out.print(e);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "File Processing Error", "File", HEIGHT);
                dispose();
                new login().setVisible(true);
            }
        } catch (HeadlessException e) {
            System.out.println("oops \n" + e);
        }


    }//GEN-LAST:event_codes_app_commit_btnActionPerformed

    private void codes_quit_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codes_quit_btnMouseEntered
       codes_quit_btn.setBackground(Color.red);
    }//GEN-LAST:event_codes_quit_btnMouseEntered

    private void codes_quit_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codes_quit_btnMouseExited
       codes_quit_btn.setBackground(Color.GRAY);
    }//GEN-LAST:event_codes_quit_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new codes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alarm_chk;
    private javax.swing.JTextField alarm_office_txt;
    private javax.swing.JButton codes_app_commit_btn;
    private javax.swing.JButton codes_quit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox office_key_chk;
    private javax.swing.JTextField open_off_txt;
    private javax.swing.JCheckBox print_chk;
    private javax.swing.JCheckBox tel_chk;
    // End of variables declaration//GEN-END:variables
}
