/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_package;

import file_op.FileOperations;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Doreen Midecha
 */
public class Rights_form extends javax.swing.JFrame {
//    variable declarations 

    FileOperations fo;
    thread_file_2 tf;

    /**
     * Creates new form Rights_form
     */
    public Rights_form() {
        initComponents();
        tf = new thread_file_2(new writing_splash(), 40, new access());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        region_combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        designation_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        right_form_submit_btn = new javax.swing.JButton();
        exit_right_form_btn = new javax.swing.JButton();
        aprovertxt = new javax.swing.JLabel();
        dept_combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        user_type_combo = new javax.swing.JComboBox<>();
        user_name_txt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USER RIGHTS DETAILS");
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER USER RIGHTS DETAILS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        region_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "HQ", "NC", "MSA", "KSM", "DAR", "KIT", "MERU", "NYERI", "" }));
        region_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                region_comboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("REGION :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("USERNAME:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DESIGNATION :");

        designation_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designation_txtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DEPARTMENT:");

        right_form_submit_btn.setText("SUBMIT");
        right_form_submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_form_submit_btnActionPerformed(evt);
            }
        });

        exit_right_form_btn.setText("EXIT");
        exit_right_form_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_right_form_btnActionPerformed(evt);
            }
        });

        dept_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "GB", "SALES", "FINANCE", "ADJUDICATOR", "ICT", "" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("USER TYPE :");

        user_type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Existing User", "New User" }));
        user_type_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_type_comboActionPerformed(evt);
            }
        });

        user_name_txt.setEditable(true);
        user_name_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Admin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dept_combo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user_type_combo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(region_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(designation_txt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(right_form_submit_btn)
                                .addGap(39, 39, 39)
                                .addComponent(exit_right_form_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(user_name_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aprovertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(user_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(region_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designation_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit_right_form_btn)
                    .addComponent(right_form_submit_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aprovertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void region_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_region_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_region_comboActionPerformed

    private void designation_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designation_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designation_txtActionPerformed

    private void exit_right_form_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_right_form_btnActionPerformed
//       clear all the fields

//      close the rights form jframe prompt login
        dispose();

//        display login frame
        new login().setVisible(true);

    }//GEN-LAST:event_exit_right_form_btnActionPerformed

    private void right_form_submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_form_submit_btnActionPerformed
//        local variable declaration 
        String region;
        String user;
        String desig;
        String dept;
        String usertype;
        boolean status = false;
//        get user inputs and variable declarations
        region = region_combo.getSelectedItem().toString();
        user = user_name_txt.getSelectedItem().toString();
        dept = dept_combo.getSelectedItem().toString();
        desig = designation_txt.getText();
        usertype = user_type_combo.getSelectedItem().toString();

//        validate user input
        if (region.isEmpty() || user.isEmpty() || dept.isEmpty() || desig.isEmpty() || usertype.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Empty values are not accepted !!");
        } else {
//            re-format data
            Date dt = new Date();
            String date = dt.toString();
            String reg = "REGION_ _ _ _: " + region.toUpperCase();
            String usr = "USER_ _ _ _ _: " + desig.toUpperCase() + " " + user.toUpperCase();
            String dp = "DEPARTMENT_ _: " + dept.toUpperCase();
            String ut = "USER TYPE_ _ : " + usertype.toUpperCase();
            fo = new FileOperations();
//            check if file exists proceed
            if (fo.fileExists()) {
//                close this frmae 
                dispose();
//                display the message
                JOptionPane.showMessageDialog(rootPane, "File already exits Proceed");
//              open applications file 
                new access().setVisible(true);
            } else {
//          create file
                boolean file = fo.createFile();
//          start file thread
                tf.start();
//          write to file
                if (file) {

//                write to file
                    String[] results = {date, " ", reg, usr, dp, ut};
                    fo.writeToFile(results);
                }

                //      dispose  current jframe
                dispose();
            }

//            for (String result : results) {
//               System.out.println(result);
//            }  
        }

//         fetch rights request form
//          dispose rights form jframe

    }//GEN-LAST:event_right_form_submit_btnActionPerformed

    private void user_type_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_type_comboActionPerformed
        if (user_type_combo.getSelectedIndex() == 1) {
            user_name_txt.setEditable(false);
             user_name_txt.enable(true);
        } else {
            user_name_txt.setEditable(true);
            user_name_txt.enable(false);
        }
    }//GEN-LAST:event_user_type_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rights_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rights_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rights_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rights_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rights_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aprovertxt;
    private javax.swing.JComboBox<String> dept_combo;
    private javax.swing.JTextField designation_txt;
    private javax.swing.JButton exit_right_form_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> region_combo;
    private javax.swing.JButton right_form_submit_btn;
    private javax.swing.JComboBox<String> user_name_txt;
    private javax.swing.JComboBox<String> user_type_combo;
    // End of variables declaration//GEN-END:variables
}
